### PR TITLE
link to HTTP/2 spec

### PR DESCRIPTION
**Pull request by chadwhitacre**
I need to get up to speed on HTTP/2. Do I have the right link?

### CODE REVIEW

**Comment by sigmavirus24** [comment]
You do. It's in the final stages though, so don't expect it to change much unless the call for comments produces some spectacular problems.

**Comment by chadwhitacre** [comment]
> You do. It's in the final stages

Perfect, thanks. :-)

**Comment by sigmavirus24** [comment]
An alternative link: https://datatracker.ietf.org/doc/draft-ietf-httpbis-http2/

**Comment by sigmavirus24** [comment]
You can also follow the last call discussion that [started on Dec 31](http://lists.w3.org/Archives/Public/ietf-http-wg/2014OctDec/0982.html) via [this thread](http://lists.w3.org/Archives/Public/ietf-http-wg/2014OctDec/0982.html). Note, there's a lot of fund being spread by PHK and recirculated in that thread.

**Comment by Lukasa** [comment]
While we're here, [this](http://daniel.haxx.se/http2/) document is a great resource.

**Comment by auvipy** [comment]
the spec is finalized

**Pull request closed without merging**
